/* tray-themes.js — the five tray theme palettes (CSS custom-property values
   per theme) and applyTrayTheme(), which writes them onto the document root
   and swaps the tray/background texture images. Depends on assets.js
   (textureUrl()) to resolve those images, and on colour-schemes.js
   (COLOUR_SCHEMES, TRAY_DEFAULT_SCHEME) only for the auto-pairing done by the
   theme-select listener in main.js; textures live in textures/ and are
   pre-generated by gen_textures.py. */

/* =========================================================================
   TRAY TEXTURE FILES
   Tray overlays:   textures/tray_<theme>.png  (768×768, RGBA)
   Backgrounds:     textures/bg_<theme>.jpg    (1920×1080, RGB)
   Both generated once by gen_textures.py and referenced as static files.
   ========================================================================= */

const TRAY_THEMES = {
  'green-felt': {
    label: 'Green Felt',
    'color-text':            '#f4ead2',
    'color-text-secondary':  '#cfc6ab',
    'color-title':           '#f4ead2',
    'color-dropdown-label':  '#cfc6ab',
    'color-modifier-label':  '#cfc6ab',
    'color-accent':          '#c9a24b',
    'color-accent-secondary':'#8d7438',
    'color-die-stroke':      '#16382b',
    'color-picker-icon':     '#f4ead2',
    'color-dropdown-bg':     '#1f4d3a',
    'color-tray-bg':         '#0e451c',
    'color-btn-clear':       '#d8654a',
    'color-btn-bg':          '#f4ead20f',
    'color-btn-border':      '#f4ead238',
    'color-btn-hover':       '#f4ead224',
    'color-roll-btn-top':    '#c9a24b',
    'color-roll-btn-bottom': '#8d7438',
    'color-roll-btn-text':   '#0f2a20',
    'color-adv-btn-bg':      '#229e49d0',
    'color-adv-btn-border':  '#11672cfb',
    'color-adv-btn-hover':   '#9acdaa33',
    'color-disadv-btn-bg':   '#af3e25be',
    'color-disadv-btn-border':'#af3e25',
    'color-disadv-btn-hover':'#c47a6a33',
    'color-separator':       '#f4ead22e',
    'color-separator-subtle':'#f4ead21a',
    'font-title': "'Almendra', serif",
    'font-ui':    "'JetBrains Mono', monospace",
  },
  'midnight-velvet': {
    label: 'Midnight Velvet',
    'color-text':            '#e8d8ff',
    'color-text-secondary':  '#a898cc',
    'color-title':           '#e8d8ff',
    'color-dropdown-label':  '#a898cc',
    'color-modifier-label':  '#a898cc',
    'color-accent':          '#b090f0',
    'color-accent-secondary':'#7060b0',
    'color-die-stroke':      '#06041a',
    'color-picker-icon':     '#e8d8ff',
    'color-dropdown-bg':     '#0d0820',
    'color-tray-bg':         '#2a1733',
    'color-btn-clear':       '#c060d0',
    'color-btn-bg':          '#b4a0ff12',
    'color-btn-border':      '#b090f047',
    'color-btn-hover':       '#b090f029',
    'color-roll-btn-top':    '#b090f0',
    'color-roll-btn-bottom': '#7060b0',
    'color-roll-btn-text':   '#0a0618',
    'color-adv-btn-bg':      '#64b4ff1a',
    'color-adv-btn-border':  '#64b4ffa6',
    'color-adv-btn-hover':   '#64b4ff38',
    'color-disadv-btn-bg':   '#c850dc1a',
    'color-disadv-btn-border':'#c850dca6',
    'color-disadv-btn-hover':'#c850dc38',
    'color-separator':       '#b090f038',
    'color-separator-subtle':'#b090f01c',
    'font-title': "'Uncial Antiqua', cursive",
    'font-ui':    "'Share Tech Mono', monospace",
  },
  'parchment': {
    label: 'Ancient Parchment',
    'color-text':            '#2a1800',
    'color-text-secondary':  '#5a3800',
    'color-title':           '#2a1800',
    'color-dropdown-label':  '#5a3800',
    'color-modifier-label':  '#5a3800',
    'color-accent':          '#6a3010',
    'color-accent-secondary':'#8a5020',
    'color-die-stroke':      '#a88850',
    'color-picker-icon':     '#2a1800',
    'color-dropdown-bg':     '#c8a870',
    'color-tray-bg':         '#e0bf77',
    'color-btn-clear':       '#c04010',
    'color-btn-bg':          '#2a180014',
    'color-btn-border':      '#6a301059',
    'color-btn-hover':       '#6a301029',
    'color-roll-btn-top':    '#6a3010',
    'color-roll-btn-bottom': '#8a5020',
    'color-roll-btn-text':   '#f8ecd0',
    'color-adv-btn-bg':      '#2864281a',
    'color-adv-btn-border':  '#28642899',
    'color-adv-btn-hover':   '#28642833',
    'color-disadv-btn-bg':   '#a028141a',
    'color-disadv-btn-border':'#a0281499',
    'color-disadv-btn-hover':'#a0281433',
    'color-separator':       '#6a301040',
    'color-separator-subtle':'#6a301021',
    'font-title': "'IM Fell English', serif",
    'font-ui':    "'Courier Prime', monospace",
  },
  'weathered-slate': {
    label: 'Weathered Slate',
    'color-text':            '#e0d4b8',
    'color-text-secondary':  '#e0d4b8',
    'color-title':           '#e0d4b8',
    'color-dropdown-label':  '#e0d4b8',
    'color-modifier-label':  '#e0d4b8',
    'color-accent':          '#7f7f7f',
    'color-accent-secondary':'#3a9880',
    'color-die-stroke':      '#046982',
    'color-picker-icon':     '#e8eef4',
    'color-dropdown-bg':     '#2a2e34',
    'color-tray-bg':         '#141820',
    'color-btn-clear':       '#e06050',
    'color-btn-bg':          '#e8eef40f',
    'color-btn-border':      '#60c8b047',
    'color-btn-hover':       '#60c8b024',
    'color-roll-btn-top':    '#500a20',
    'color-roll-btn-bottom': '#500a20',
    'color-roll-btn-text':   '#e0d4b8',
    'color-adv-btn-bg':      '#50c8a01a',
    'color-adv-btn-border':  '#50c8a0a6',
    'color-adv-btn-hover':   '#50c8a038',
    'color-disadv-btn-bg':   '#e060501a',
    'color-disadv-btn-border':'#e06050a6',
    'color-disadv-btn-hover':'#e0605038',
    'color-separator':       '#60c8b038',
    'color-separator-subtle':'#60c8b01c',
    'font-title': "'Rajdhani', sans-serif",
    'font-ui':    "'Share Tech Mono', monospace",
  },
  'ivory-marble': {
    label: 'Ivory Marble',
    'color-text':            '#1a1410',
    'color-text-secondary':  '#96475c',
    'color-title':           '#1a1410',
    'color-dropdown-label':  '#96475c',
    'color-modifier-label':  '#96475c',
    'color-accent':          '#63001a',
    'color-accent-secondary':'#96475c',
    'color-die-stroke':      '#ffffff',
    'color-picker-icon':     '#1a1410',
    'color-dropdown-bg':     '#e8e0d4',
    'color-tray-bg':         '#ddd6c8',
    'color-btn-clear':       '#63001a',
    'color-btn-bg':          '#1a141012',
    'color-btn-border':      '#63001a4c',
    'color-btn-hover':       '#63001a24',
    'color-roll-btn-top':    '#63001a',
    'color-roll-btn-bottom': '#63001a',
    'color-roll-btn-text':   '#f8f0e8',
    'color-adv-btn-bg':      '#1e641e14',
    'color-adv-btn-border':  '#1e641e8c',
    'color-adv-btn-hover':   '#1e641e2e',
    'color-disadv-btn-bg':   '#8a1a1014',
    'color-disadv-btn-border':'#8a1a108c',
    'color-disadv-btn-hover':'#8a1a102e',
    'color-separator':       '#2a1e8038',
    'color-separator-subtle':'#2a1e801c',
    'font-title': "'Playfair Display', serif",
    'font-ui':    "'Courier Prime', monospace",
  },
};

function applyTrayTheme(themeKey) {
  const theme = TRAY_THEMES[themeKey];
  if (!theme) return;
  const root = document.documentElement;
  const varNames = [
    'color-text','color-text-secondary','color-title','color-dropdown-label','color-modifier-label',
    'color-accent','color-accent-secondary',
    'color-die-stroke','color-picker-icon',
    'color-dropdown-bg','color-tray-bg',
    'color-btn-bg','color-btn-border','color-btn-hover','color-btn-clear',
    'color-roll-btn-top','color-roll-btn-bottom','color-roll-btn-text',
    'color-adv-btn-bg','color-adv-btn-border','color-adv-btn-hover',
    'color-disadv-btn-bg','color-disadv-btn-border','color-disadv-btn-hover',
    'color-separator','color-separator-subtle',
    'font-title','font-ui',
  ];
  varNames.forEach(v => {
    if (theme[v] !== undefined) root.style.setProperty('--' + v, theme[v]);
  });

  // Apply pre-generated tray surface texture (PNG). textureUrl() (assets.js)
  // always returns an absolute or data: URL: css/tray.css reads
  // --tray-texture via var(), and a relative url() inside a custom property
  // resolves against the stylesheet that *uses* the variable (css/tray.css),
  // not this script or index.html — so a plain relative path here would 404
  // against css/textures/ instead of textures/.
  root.style.setProperty('--tray-texture', `url("${textureUrl(`tray_${themeKey}.png`)}")`);

  // Swap background image (JPEG, scales via CSS background-size:cover)
  document.getElementById('bg-layer').style.backgroundImage = `url("${textureUrl(`bg_${themeKey}.jpg`)}")`;

  // Update the option/optgroup background in the colour-scheme-selects to match
  document.querySelectorAll('.colour-scheme-select option, .colour-scheme-select optgroup').forEach(opt => {
    opt.style.background = theme['color-dropdown-bg'];
    opt.style.color = theme['color-text'];
  });
}
